import { StateGraph, Annotation, START, END, type GraphNode } from "@langchain/langgraph"
import z from "zod";
import { mistralAIModel, cohereModel } from "./model.ai.js";
import { HumanMessage } from "langchain";

const state = Annotation.Root({
    problem: Annotation<string>(),
    solution_1: Annotation<string>(),
    solution_2: Annotation<string>(),
    judge: Annotation<{
        solution_1_score: number;
        solution_2_score: number;
        solution_1_reasoning: string;
        solution_2_reasoning: string;
    }>()
})


const solutionNode: GraphNode<typeof state> = async (state) => {

    const [mistralResponse, cohereResponse] = await Promise.all([
        mistralAIModel.invoke(state.problem),
        cohereModel.invoke(state.problem)
    ])

    return {
        solution_1: mistralResponse.content as string,
        solution_2: cohereResponse.content as string,
    }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state

    const structuredModel = mistralAIModel.withStructuredOutput(
        z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
            solution_1_reasoning: z.string(),
            solution_2_reasoning: z.string(),
        })
    );

    const judgeResponse = await structuredModel.invoke([
        new HumanMessage(`
            System Prompt: You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.

            Problem: ${problem}
            Solution 1: ${solution_1}
            Solution 2: ${solution_2}
            Please evaluate the solutions and provide scores and reasoning.
        `)
    ]);

    const {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning
    } = judgeResponse;

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    };

}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile()

export default async function (problem: string) { 

    const result = await graph.invoke({
        problem: problem
    })

    return result

}